fixtures:
  symlinks:
    confluence: "#{source_dir}"
  repositories:
    archive: "https://github.com/voxpupuli/puppet-archive.git"
    staging: "https://github.com/voxpupuli/puppet-staging.git"
    stdlib:  "https://github.com/puppetlabs/puppetlabs-stdlib.git"
